apiVersion: v2
name: vault
description: HashiCorp Vault for WRCBot
type: application
version: 0.1.0
dependencies:
  - name: vault
    version: 0.25.0
    repository: https://helm.releases.hashicorp.com
