replicaCount: 1

image:
  repository: hashicorp/vault
  tag: "1.15.2"

vault:
  # Root token for initial setup (change this in production)
  rootToken: "root"
  # Enable production mode (not dev mode)
  mode: "production"

storage:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 4Gi
  path: /home/ec2-user/vaultdata

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

service:
  type: ClusterIP
  port: 8200

config:
  backend:
    type: file
    path: /vault/file
  listener:
    tcp:
      address: 0.0.0.0:8200
      tls_disable: 1