apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/coolshiva123/wrcbot.git'   # <-- Change to your repo URL
    targetRevision: HEAD                               # or a branch/tag/commit
    path: redis                                       # path to your Helm chart in the repo
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wrcbot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true