apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault.fullname" . }}-config
  labels:
    {{- include "vault.labels" . | nindent 4 }}
data:
  vault.hcl: |
    {{- if .Values.vault.storage }}
    storage "{{ .Values.vault.storage.type }}" {
      {{- range $key, $value := .Values.vault.storage.config }}
      {{ $key }} = "{{ $value }}"
      {{- end }}
    }
    {{- end }}
    
    {{- if .Values.vault.listener }}
    listener "tcp" {
      {{- range $key, $value := .Values.vault.listener.tcp }}
      {{ $key }} = {{ if eq (kindOf $value) "string" }}"{{ $value }}"{{ else }}{{ $value }}{{ end }}
      {{- end }}
    }
    {{- end }}
    
    {{- if .Values.vault.ui }}
    ui = {{ .Values.vault.ui }}
    {{- end }}
    
    cluster_addr = "https://POD_IP:8201"
    api_addr = "http://POD_IP:8200"
