apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  config.hcl: |
    storage "file" {
      path = "/home/ec2-user/vaultdata"
    }
    
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }
    
    api_addr = "http://<your-vault-address>:8200"
    cluster_addr = "http://<your-vault-address>:8201"