apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault.fullname" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vault.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vault.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vault.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.persistence.enabled }}
      initContainers:
        - name: vault-init
          image: busybox:1.35
          command: 
            - sh
            - -c
            - |
              # Create directory and set permissions for Minikube
              mkdir -p /vault/data
              chown -R 1000:1000 /vault/data
              chmod -R 755 /vault/data
              echo "Vault data directory initialized for Minikube"
          volumeMounts:
            - name: vault-data
              mountPath: /vault/data
          securityContext:
            runAsUser: 0
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
            - name: cluster
              containerPort: 8201
              protocol: TCP
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: {{ .Values.vault.devRootToken | quote }}
            - name: VAULT_DEV_LISTEN_ADDRESS
              value: "0.0.0.0:8200"
            {{- if .Values.vault.config }}
            - name: VAULT_LOCAL_CONFIG
              value: |
                {{- .Values.vault.config | toYaml | nindent 16 }}
            {{- end }}
          command:
            - "vault"
          args:
            - "server"
            {{- if .Values.vault.dev }}
            - "-dev"
            {{- else }}
            - "-config=/vault/config"
            {{- end }}
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: vault-data
              mountPath: /vault/data
            {{- end }}
            {{- if not .Values.vault.dev }}
            - name: vault-config
              mountPath: /vault/config
              readOnly: true
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: vault-data
          persistentVolumeClaim:
            claimName: {{ include "vault.fullname" . }}-data
        {{- end }}
        {{- if not .Values.vault.dev }}
        - name: vault-config
          configMap:
            name: {{ include "vault.fullname" . }}-config
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
