apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault.fullname" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vault.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vault.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: vault
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - name: http
          containerPort: 8200
          protocol: TCP
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: {{ .Values.vault.devRootToken | quote }}
        - name: VAULT_DEV_LISTEN_ADDRESS
          value: "0.0.0.0:8200"
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: vault-storage
          mountPath: /vault/file
      volumes:
      - name: vault-storage
        persistentVolumeClaim:
          claimName: {{ include "vault.fullname" . }}-pvc