apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault.fullname" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vault.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vault.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: vault-sa
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: vault-config-init
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
          capabilities:
            drop:
              - ALL
        command:
        - /bin/sh
        - -c
        - |
          cat > /vault/config/vault.hcl << EOF
          storage "file" {
            path = "/vault/file"
          }
          listener "tcp" {
            address = "0.0.0.0:8200"
            tls_disable = 1
            cluster_address = "0.0.0.0:8201"
          }
          api_addr = "http://0.0.0.0:8200"
          cluster_addr = "http://0.0.0.0:8201"
          ui = true
          disable_mlock = true
          EOF
        volumeMounts:
        - name: vault-config
          mountPath: /vault/config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
      - name: vault-init
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
          capabilities:
            drop:
              - ALL
        command: ["/bin/sh", "/scripts/init.sh"]
        env:
        - name: VAULT_ADDR
          value: "http://127.0.0.1:8200"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-keys
              key: root-token
        volumeMounts:
        - name: vault-init-script
          mountPath: /scripts
        - name: vault-token
          mountPath: /home/vault/.vault-token
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
      containers:
      - name: vault
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
          capabilities:
            drop:
              - ALL
        ports:
        - name: http
          containerPort: 8200
          protocol: TCP
        - name: cluster
          containerPort: 8201
          protocol: TCP
        command:
        - vault
        args:
        - server
        - -config=/vault/config/vault.hcl
        env:
        - name: VAULT_API_ADDR
          value: "http://0.0.0.0:8200"
        - name: VAULT_CLUSTER_ADDR
          value: "http://0.0.0.0:8201"
        - name: VAULT_LOG_LEVEL
          value: "debug"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: vault-config
          mountPath: /vault/config
        - name: vault-storage
          mountPath: /vault/file
        - name: vault-token
          mountPath: /home/vault/.vault-token
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - vault status -tls-skip-verify
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true&sealedcode=200&uninitcode=200
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
      volumes:
      - name: vault-storage
        persistentVolumeClaim:
          claimName: vault-pvc
      - name: vault-config
        emptyDir: {}
      - name: vault-init-script
        configMap:
          name: vault-init-script
          defaultMode: 0755
      - name: vault-token
        emptyDir:
          medium: Memory