apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault.fullname" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vault.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vault.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: vault-config-init
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command:
        - /bin/sh
        - -c
        - |
          cat > /vault/config/vault.hcl << EOF
          storage "file" {
            path = "/vault/file"
          }
          listener "tcp" {
            address = "0.0.0.0:8200"
            tls_disable = 1
          }
          api_addr = "http://0.0.0.0:8200"
          cluster_addr = "http://0.0.0.0:8201"
          ui = true
          disable_mlock = true
          EOF
        volumeMounts:
        - name: vault-config
          mountPath: /vault/config
      containers:
      - name: vault
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - name: http
          containerPort: 8200
          protocol: TCP
        - name: cluster
          containerPort: 8201
          protocol: TCP
        command:
        - vault
        args:
        - server
        - -config=/vault/config/vault.hcl
        env:
        - name: VAULT_API_ADDR
          value: "http://0.0.0.0:8200"
        - name: VAULT_CLUSTER_ADDR
          value: "http://0.0.0.0:8201"
        - name: VAULT_LOG_LEVEL
          value: "debug"
        volumeMounts:
        - name: vault-config
          mountPath: /vault/config
        - name: vault-storage
          mountPath: /vault/file
      - name: vault-init
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["/bin/sh", "/scripts/init.sh"]
        env:
        - name: VAULT_ADDR
          value: "http://127.0.0.1:8200"
        - name: VAULT_TOKEN
          value: "{{ .Values.vault.rootToken }}"
        - name: VAULT_LOG_LEVEL
          value: "debug"
        volumeMounts:
        - name: vault-init-script
          mountPath: /scripts
        - name: vault-config
          mountPath: /vault/config
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: vault-storage
        persistentVolumeClaim:
          claimName: {{ include "vault.fullname" . }}-pvc
      - name: vault-config
        emptyDir: {}
      - name: vault-init-script
        configMap:
          name: vault-init-script
          defaultMode: 0755