apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
  {{- range .Values.storage.accessModes }}
    - {{ . }}
  {{- end }}
  storageClassName: standard
  hostPath:
    path: {{ .Values.storage.path }}