apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vault.fullname" . }}-pvc
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.storage.accessModes }}
    - {{ . }}
  {{- end }}
  storageClassName: standard
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  volumeName: {{ include "vault.fullname" . }}-pv v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  volumeName: vault-pv