apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "vault.fullname" . }}-pv
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
  {{- range .Values.storage.accessModes }}
    - {{ . }}
  {{- end }}
  storageClassName: standard
  hostPath:
    path: {{ .Values.storage.path }}