apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "vault.fullname" . }}-pv
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass | default "manual" }}
  hostPath:
    path: {{ .Values.persistence.hostPath.path }}
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          {{- range .Values.persistence.hostPath.allowedNodes }}
          - {{ . }}
          {{- end }}
