apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: ""
  volumeName: vault-pv # Explicitly bind to our PV
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.storage.path }}
    type: DirectoryOrCreate
