{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vault.fullname" . }}-data
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | default "manual" }}
  {{- if .Values.persistence.hostPath.enabled }}
  selector:
    matchLabels:
      {{- include "vault.labels" . | nindent 6 }}
  {{- end }}
{{- end }}
