apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wrcbot.fullname" . }}-config
  labels:
    {{- include "wrcbot.labels" . | nindent 4 }}
data:
  config.py: |
    import os

    BACKEND = 'SlackV3'
    BOT_DATA_DIR = '/errbot/data'
    BOT_EXTRA_PLUGIN_DIR = '/errbot/src/plugins'
    BOT_LOG_FILE = '/errbot/errbot.log'
    BOT_EXTRA_BACKEND_DIR = '/opt/errbot/backend'
    BOT_LOG_LEVEL = {{ .Values.bot.logLevel | default "DEBUG" | quote }}

    # Read sensitive configs from environment variables
    BOT_ADMINS = tuple(admin.strip() for admin in os.getenv('BOT_ADMINS', '').split(',') if admin.strip())
    BOT_IDENTITY = {
        'token': os.getenv('SLACK_TOKEN', ''),
        'signing_secret': os.getenv('SLACK_SIGNING_SECRET', ''),
        'app_token': os.getenv('SLACK_APP_TOKEN', '')
    }
    BOT_PREFIX = os.getenv('BOT_PREFIX', '!')
  # Bot configuration that doesn't contain secrets
  {{- if .Values.bot.config }}
  {{- toYaml .Values.bot.config | nindent 2 }}
  {{- end }}
  # Default configuration
  log_level: "INFO"
  plugin_dir: "/app/plugins"
  data_dir: "/tmp/data"
