apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wrcbot.fullname" . }}
  labels:
    {{- include "wrcbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wrcbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/role: 'wrcbot-role'
        vault.hashicorp.com/namespace: '{{ .Release.Namespace }}'
        vault.hashicorp.com/auth-path: 'auth/kubernetes'
        vault.hashicorp.com/secret-volume-path: '/vault/secrets'
        vault.hashicorp.com/agent-init-first: 'true'
        vault.hashicorp.com/agent-inject-secret-env: 'secret/wrcbot-config'
        vault.hashicorp.com/agent-inject-template-env: |
          #!/bin/sh
          set -e
          echo "=== Debug: Starting template processing ==="
          
          {{ "{{" }} with secret "secret/wrcbot-config" {{ "}}" }}
          {{ "{{" }} $config := .Data.config | parseJSON {{ "}}" }}
          
          echo "=== Debug: Parsed config data ==="
          echo "Setting BOT_ADMINS..."
          export BOT_ADMINS="{{ "{{" }} range $i, $e := $config.BOT_ADMINS {{ "}}" }}{{ "{{" }}if $i{{ "}}" }},{{ "{{" }}end{{ "}}" }}{{ "{{" }}$e{{ "}}" }}{{ "{{" }} end {{ "}}" }}"
          
          echo "Setting Slack credentials..."
          export SLACK_TOKEN="{{ "{{" }} $config.BOT_IDENTITY.token {{ "}}" }}"
          export SLACK_SIGNING_SECRET="{{ "{{" }} $config.BOT_IDENTITY.signing_secret {{ "}}" }}"
          export SLACK_APP_TOKEN="{{ "{{" }} $config.BOT_IDENTITY.app_token {{ "}}" }}"
          
          echo "Setting BOT_PREFIX..."
          export BOT_PREFIX="{{ "{{" }} $config.BOT_PREFIX {{ "}}" }}"
          
          echo "=== Debug: Environment variables set successfully ==="
          {{ "{{" }} end {{ "}}" }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wrcbot.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: wrcbot-sa
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "wrcbot.fullname" . }}-config
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /errbot/src
              source /vault/secrets/env
              echo "Configuration ready for inspection. Pod sleeping..."
              sleep infinity
          volumeMounts:
            - name: config-volume
              mountPath: /errbot/src/config.py
              subPath: config.py
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            {{- range $key, $value := .Values.bot.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if not .Values.bot.disableHealthChecks }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
