apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wrcbot.fullname" . }}
  labels:
    {{- include "wrcbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wrcbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/role: 'wrcbot-role'
        vault.hashicorp.com/namespace: '{{ .Release.Namespace }}'
        vault.hashicorp.com/auth-path: 'auth/kubernetes'
        # Single template for both env and config.py
        vault.hashicorp.com/agent-inject-secret-config.py: 'secret/wrcbot-config'
        vault.hashicorp.com/agent-inject-file-config.py: '/vault/secrets/config.py'
        vault.hashicorp.com/agent-inject-template-config.py: |
          BACKEND = 'SlackV3'
          BOT_DATA_DIR = '/errbot/data'
          BOT_EXTRA_PLUGIN_DIR = '/errbot/src/plugins'
          BOT_LOG_FILE = '/errbot/errbot.log'
          BOT_EXTRA_BACKEND_DIR = '/opt/errbot/backend'
          BOT_LOG_LEVEL = 'DEBUG'

          {{ "{{" }} with secret "secret/wrcbot-config" }}
          {{ "{{" }} with .Data }}
          {{ "{{" }} with .config | parseJSON }}
          # Bot admins list from Vault
          BOT_ADMINS = tuple({{ "{{" }} .BOT_ADMINS | toJSON }})

          # Bot identity configuration from Vault
          BOT_IDENTITY = {
              'token': '{{ "{{" }} .BOT_IDENTITY.token }}',
              'signing_secret': '{{ "{{" }} .BOT_IDENTITY.signing_secret }}',
              'app_token': '{{ "{{" }} .BOT_IDENTITY.app_token }}'
          }

          # Bot prefix from Vault
          BOT_PREFIX = '{{ "{{" }} .BOT_PREFIX }}'
          {{ "{{" }} end }}
          {{ "{{" }} end }}
          {{ "{{" }} end }}
        # Inject to temporary location first
        vault.hashicorp.com/agent-inject-file-config.py: '/vault/secrets/config.py'
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wrcbot.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: wrcbot-sa
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Checking original config.py content..."
              echo "=== Original config.py ===" > /errbot/config_py_content.txt
              cat /errbot/src/config.py >> /errbot/config_py_content.txt
              
              echo "Copying Vault config.py..."
              cp /vault/secrets/config.py /errbot/src/config.py
              
              echo "=== New config.py ===" >> /errbot/config_py_content.txt
              cat /errbot/src/config.py >> /errbot/config_py_content.txt
              echo "Current time: $(date)" >> /errbot/config_py_content.txt
              
              echo "Writing environment variables to file for verification..."
              env | grep -E "BOT_|SLACK_" > /errbot/vault_env_vars.txt
              echo "Current time: $(date)" >> /errbot/vault_env_vars.txt
              
              echo "Files ready for inspection. Sleeping..."
              sleep infinity
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            {{- range $key, $value := .Values.bot.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if not .Values.bot.disableHealthChecks }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
