apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wrcbot.fullname" . }}
  labels:
    {{- include "wrcbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wrcbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/role: 'wrcbot-role'
        vault.hashicorp.com/namespace: '{{ .Release.Namespace }}'
        vault.hashicorp.com/auth-path: 'auth/kubernetes'
        vault.hashicorp.com/agent-inject-secret-env: 'secret/wrcbot-config'
        vault.hashicorp.com/agent-inject-template-env: |
          #!/bin/sh
          {{ "{{" }} with secret "secret/wrcbot-config" }}
          {{ "{{" }} with .Data }}
          {{ "{{" }} $config := .config | parseJSON }}
          export BOT_ADMINS='{{ "{{" }} $config.BOT_ADMINS | toJSON }}'
          export SLACK_TOKEN='{{ "{{" }} $config.BOT_IDENTITY.token }}'
          export SLACK_SIGNING_SECRET='{{ "{{" }} $config.BOT_IDENTITY.signing_secret }}'
          export SLACK_APP_TOKEN='{{ "{{" }} $config.BOT_IDENTITY.app_token }}'
          export BOT_PREFIX='{{ "{{" }} $config.BOT_PREFIX }}'
          {{ "{{" }} end }}
          {{ "{{" }} end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wrcbot.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: wrcbot-sa
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              . /vault/secrets/env
              echo "Environment variables after sourcing:"
              env | grep -E "BOT_|SLACK_"
              echo "Configuration ready for inspection. Pod sleeping..."
              sleep infinity
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            {{- range $key, $value := .Values.bot.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if not .Values.bot.disableHealthChecks }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
