apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wrcbot.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "wrcbot.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "wrcbot.name" . }}
    spec:
      containers:
        - name: errbot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.slack.existingSecret }}
                  key: {{ .Values.slack.existingSecretKey }}
          ports:
            - containerPort: 3141
          resources:
            {{- toYaml .Values.resources | nindent 12 }}