apiVersion: v1
kind: Service
metadata:
  name: {{ include "wrcbot.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3141
      protocol: TCP
      name: http
  selector:
    app: {{ include "wrcbot.name" . }}