{{- if .Values.vault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wrcbot.vaultSecretName" . }}
  labels:
    {{- include "wrcbot.labels" . | nindent 4 }}
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "wrcbot"
    vault.hashicorp.com/agent-inject-secret-config: {{ .Values.vault.secretPath | quote }}
    vault.hashicorp.com/agent-inject-template-config: |
      {{`{{- with secret `}}{{ .Values.vault.secretPath | quote }}{{` -}}
      {{- range $k, $v := .Data.data }}
      {{ $k }}={{ $v }}
      {{- end }}
      {{- end }}`}}
type: Opaque
data:
  # Placeholder - actual secrets will be injected by Vault Agent
  placeholder: {{ "placeholder" | b64enc }}
{{- end }}
