apiVersion: v1
kind: Secret
metadata:
  name: wrcbot-sa-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: wrcbot-sa
type: kubernetes.io/service-account-token
