apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Lower number, runs first
spec:
  project: wrcbot
  source:
    repoURL: 'https://github.com/coolshiva123/wrcbot.git'
    targetRevision: HEAD
    path: helmchart/vault
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wrcbot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: vault-auth-delegator
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels