apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wrcbot-apps
  namespace: argocd
spec:
  project: wrcbot
  source:
    repoURL: 'https://github.com/coolshiva123/wrcbot.git'
    targetRevision: HEAD
    path: argoapp/redis         # Directory containing redisapp.yaml
    directory:
      recurse: true             # Allows Argo CD to find Application manifests recursively
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true