apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wrcbot-apps
  namespace: argocd
spec:
  project: wrcbot
  source:
    repoURL: 'https://github.com/coolshiva123/wrcbot.git'
    targetRevision: HEAD
    path: argoapp
    directory:
      recurse: false  # Don't recurse into subdirectories
      include: '{redisapp.yaml,rabbitmqapp.yaml,vaultapp.yaml,wrcbotapp.yaml,huggingface.yaml}'  # Added huggingface Helm chart manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true