apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wrcbot
  namespace: argocd
spec:
  project: wrcbot
  source:
    repoURL: 'https://github.com/coolshiva123/wrcbot.git'
    targetRevision: HEAD
    path: helmchart/wrcbot
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wrcbot
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/env
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: vault-auth-delegator
      jsonPointers:
        - /metadata
        - /roleRef
        - /subjects
