apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wrcbot
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Ensure this runs after Vault is ready
spec:
  project: wrcbot
  source:
    repoURL: 'https://github.com/coolshiva123/wrcbot.git'
    targetRevision: HEAD
    path: helmchart/wrcbot
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wrcbot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/env
        - /spec/template/spec/volumes
        - /spec/template/spec/initContainers
    - group: rbac.authorization.k8s.io
      kind: Role
      jsonPointers:
        - /rules
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
      jsonPointers:
        - /subjects
