apiVersion: argoproj.io/v1alpha1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: wrcbot
spec:
  type: vault
  vault:
    server: "http://vault:8200"
    path: "secret"
    version: "v1"
    auth:
      serviceAccount:
        name: wrcbot-sa
        role: wrcbot-role
