apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollama.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: 11434
      protocol: TCP
      name: http
  selector:
    app: {{ include "ollama.name" . }}
