apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rabbitmq.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "rabbitmq.name" . }}
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.amqpPort }}
            - containerPort: {{ .Values.service.managementPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}