apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.amqpPort }}
      targetPort: {{ .Values.service.amqpPort }}
      protocol: TCP
      name: amqp
    - port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.service.managementPort }}
      protocol: TCP
      name: management
  selector:
    app: {{ include "rabbitmq.name" . }}