replicaCount: 1

image:
  repository: errbotio/errbot
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3141

slack:
  existingSecret: wrcbot-slack-token
  existingSecretKey: SLACK_TOKEN
resources: {}