# Default values for wrcbot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: wrcbot
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Bot configuration
bot:
  # Environment variables for the bot
  env:
    # These will be loaded from Vault secrets
    VAULT_ADDR: "http://vault:8200"
    VAULT_TOKEN: ""

# Vault integration
vault:
  enabled: true
  secretPath: "secret/wrcbot/config"
  # Mount vault secrets as environment variables
  secrets:
    bot_token: "BOT_TOKEN"
    admin_users: "ADMIN_USERS"
    bot_signing_secret: "BOT_SIGNING_SECRET"
    bot_app_token: "BOT_APP_TOKEN"

# Persistent storage for bot data
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi
  mountPath: /app/data
