replicaCount: 1

image:
  repository: errbotio/errbot
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3141
  nodePort: 32141

slack:
  existingSecret: wrcbot-slack-token
  existingSecretKey: SLACK_TOKEN
resources: {}